name: Setsubun
version: ${project.version}
main: com.github.mcnagatuki.setsubun.Setsubun
api-version: 1.15
authors: [ Nagatuki ]
description: Setsubun Plugin
website: https://github.com/McNagatuki/Setsubun
